#include "savt/ui/ProjectConfigRecommendationService.h"

#include "savt/core/ProjectAnalysisConfig.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QRegularExpression>
#include <QSet>
#include <QStringList>

#include <filesystem>

namespace savt::ui {

namespace {

struct RuleSet {
    QStringList ignoreDirectories;
    QList<QVariantMap> moduleMerges;
    QList<QVariantMap> roleOverrides;
    QList<QVariantMap> entryOverrides;
    QList<QVariantMap> dependencyFoldRules;
};

struct FileStats {
    int totalFiles = 0;
    int qmlFiles = 0;
    int htmlFiles = 0;
    int cssFiles = 0;
    int webScriptFiles = 0;
    int cppFiles = 0;
    int jsonFiles = 0;
};

struct ScanResult {
    QString projectKindLabel;
    QStringList rootDirectories;
    QList<QVariantMap> moduleMerges;
    QStringList highConfidenceIgnoreDirectories;
    QStringList optionalIgnoreDirectories;
    QStringList ambiguousGeneratedDirectories;
    QStringList dependencyDirectories;
    QHash<QString, FileStats> scopeStats;
    QHash<QString, QStringList> entryReasons;
    QHash<QString, QStringList> presentationReasons;
    QHash<QString, QStringList> webReasons;
};

QString normalizePath(QString path) {
    path = QDir::fromNativeSeparators(path.trimmed());
    while (path.startsWith(QStringLiteral("./"))) {
        path.remove(0, 2);
    }
    while (path.endsWith(QLatin1Char('/'))) {
        path.chop(1);
    }
    return path;
}

QStringList splitSegments(const QString& path) {
    return normalizePath(path).split(QLatin1Char('/'), Qt::SkipEmptyParts);
}

QString joinSegments(const QStringList& segments) {
    return normalizePath(segments.join(QLatin1Char('/')));
}

QString entryPrefixForFilePath(const QString& filePath) {
    QStringList segments = splitSegments(filePath);
    if (segments.size() <= 1) {
        return {};
    }

    segments.removeLast();
    if (segments.isEmpty()) {
        return {};
    }

    static const QSet<QString> genericTailSegments = {
        QStringLiteral("src"),
        QStringLiteral("source"),
        QStringLiteral("sources"),
        QStringLiteral("app"),
        QStringLiteral("apps"),
        QStringLiteral("bin"),
        QStringLiteral("java"),
        QStringLiteral("kotlin")
    };

    const QString tail = segments.constLast().trimmed().toLower();
    if (segments.size() > 1 && genericTailSegments.contains(tail)) {
        segments.removeLast();
    }
    return joinSegments(segments);
}

QString lowerFileName(const QString& path) {
    return QFileInfo(path).fileName().trimmed().toLower();
}

QString lowerSuffix(const QString& path) {
    return QFileInfo(path).suffix().trimmed().toLower();
}

bool isHighConfidenceIgnoreDirectoryName(const QString& nameLower) {
    if (nameLower == QStringLiteral(".git") ||
        nameLower == QStringLiteral(".idea") ||
        nameLower == QStringLiteral(".vs") ||
        nameLower == QStringLiteral(".vscode") ||
        nameLower == QStringLiteral(".qtc_clangd") ||
        nameLower == QStringLiteral(".cache") ||
        nameLower == QStringLiteral("build") ||
        nameLower == QStringLiteral("out") ||
        nameLower == QStringLiteral("dist") ||
        nameLower == QStringLiteral("target") ||
        nameLower == QStringLiteral("bin") ||
        nameLower == QStringLiteral("obj")) {
        return true;
    }

    return nameLower.startsWith(QStringLiteral("cmake-build")) ||
           nameLower.startsWith(QStringLiteral("build-"));
}

bool isAmbiguousGeneratedDirectoryName(const QString& nameLower) {
    return nameLower == QStringLiteral("generated") ||
           nameLower == QStringLiteral("gen") ||
           nameLower == QStringLiteral("autogen") ||
           nameLower == QStringLiteral("autogenerated") ||
           nameLower == QStringLiteral(".generated");
}

bool isOptionalNoiseDirectoryName(const QString& nameLower) {
    return nameLower == QStringLiteral("test") ||
           nameLower == QStringLiteral("tests") ||
           nameLower == QStringLiteral("testdata") ||
           nameLower == QStringLiteral("docs") ||
           nameLower == QStringLiteral("doc") ||
           nameLower == QStringLiteral("example") ||
           nameLower == QStringLiteral("examples") ||
           nameLower == QStringLiteral("sample") ||
           nameLower == QStringLiteral("samples") ||
           nameLower == QStringLiteral("demo") ||
           nameLower == QStringLiteral("demos") ||
           nameLower == QStringLiteral("benchmark") ||
           nameLower == QStringLiteral("benchmarks");
}

bool isDependencyDirectoryName(const QString& nameLower) {
    return nameLower == QStringLiteral("third_party") ||
           nameLower == QStringLiteral("thirdparty") ||
           nameLower == QStringLiteral("3rdparty") ||
           nameLower == QStringLiteral("external") ||
           nameLower == QStringLiteral("vendor") ||
           nameLower == QStringLiteral("vendors") ||
           nameLower == QStringLiteral("deps") ||
           nameLower == QStringLiteral("dependency") ||
           nameLower == QStringLiteral("dependencies") ||
           nameLower == QStringLiteral("node_modules");
}

bool isPresentationHintName(const QString& nameLower) {
    return nameLower == QStringLiteral("ui") ||
           nameLower == QStringLiteral("qml") ||
           nameLower == QStringLiteral("view") ||
           nameLower == QStringLiteral("views") ||
           nameLower == QStringLiteral("page") ||
           nameLower == QStringLiteral("pages") ||
           nameLower == QStringLiteral("screen") ||
           nameLower == QStringLiteral("screens") ||
           nameLower == QStringLiteral("widget") ||
           nameLower == QStringLiteral("widgets") ||
           nameLower == QStringLiteral("window") ||
           nameLower == QStringLiteral("windows") ||
           nameLower == QStringLiteral("frontend") ||
           nameLower == QStringLiteral("content") ||
           nameLower.endsWith(QStringLiteral("content"));
}

bool isWebHintName(const QString& nameLower) {
    return nameLower == QStringLiteral("web") ||
           nameLower == QStringLiteral("www") ||
           nameLower == QStringLiteral("public");
}

bool isMainLikeFileName(const QString& fileNameLower) {
    return fileNameLower == QStringLiteral("main.cpp") ||
           fileNameLower == QStringLiteral("main.cc") ||
           fileNameLower == QStringLiteral("main.cxx") ||
           fileNameLower == QStringLiteral("main.c") ||
           fileNameLower == QStringLiteral("main.py") ||
           fileNameLower == QStringLiteral("main.js") ||
           fileNameLower == QStringLiteral("main.ts") ||
           fileNameLower == QStringLiteral("server.js") ||
           fileNameLower == QStringLiteral("app.js") ||
           fileNameLower == QStringLiteral("index.js") ||
           fileNameLower == QStringLiteral("main.qml") ||
           fileNameLower == QStringLiteral("app.qml");
}

bool isManifestFileName(const QString& fileNameLower) {
    return fileNameLower == QStringLiteral("cmakelists.txt") ||
           fileNameLower == QStringLiteral("package.json") ||
           fileNameLower == QStringLiteral("pom.xml") ||
           fileNameLower == QStringLiteral("build.gradle") ||
           fileNameLower == QStringLiteral("build.gradle.kts") ||
           fileNameLower == QStringLiteral("settings.gradle") ||
           fileNameLower == QStringLiteral("settings.gradle.kts") ||
           fileNameLower == QStringLiteral("qmldir");
}

bool isQmlLikeFile(const QString& suffixLower) {
    return suffixLower == QStringLiteral("qml") || suffixLower == QStringLiteral("ui");
}

bool isCppLikeFile(const QString& suffixLower) {
    return suffixLower == QStringLiteral("c") ||
           suffixLower == QStringLiteral("cc") ||
           suffixLower == QStringLiteral("cpp") ||
           suffixLower == QStringLiteral("cxx") ||
           suffixLower == QStringLiteral("cp") ||
           suffixLower == QStringLiteral("c++") ||
           suffixLower == QStringLiteral("ixx") ||
           suffixLower == QStringLiteral("cppm") ||
           suffixLower == QStringLiteral("h") ||
           suffixLower == QStringLiteral("hh") ||
           suffixLower == QStringLiteral("hpp") ||
           suffixLower == QStringLiteral("hxx") ||
           suffixLower == QStringLiteral("ipp") ||
           suffixLower == QStringLiteral("inl");
}

QString nativePath(const QString& path) {
    return QDir::toNativeSeparators(normalizePath(path));
}

void appendUniqueReason(QHash<QString, QStringList>& reasons, const QString& path, const QString& reason) {
    const QString cleanedPath = normalizePath(path);
    const QString cleanedReason = reason.trimmed();
    if (cleanedPath.isEmpty() || cleanedReason.isEmpty()) {
        return;
    }

    QStringList& values = reasons[cleanedPath];
    if (!values.contains(cleanedReason)) {
        values.push_back(cleanedReason);
    }
}

void appendUniqueString(QStringList& values, const QString& value) {
    const QString cleaned = normalizePath(value);
    if (!cleaned.isEmpty() && !values.contains(cleaned)) {
        values.push_back(cleaned);
    }
}

QString summarizeReasons(const QStringList& reasons, const QString& fallback) {
    if (reasons.isEmpty()) {
        return fallback;
    }

    QStringList uniqueReasons;
    for (const QString& reason : reasons) {
        const QString cleaned = reason.trimmed();
        if (!cleaned.isEmpty() && !uniqueReasons.contains(cleaned)) {
            uniqueReasons.push_back(cleaned);
        }
    }
    return uniqueReasons.isEmpty() ? fallback : uniqueReasons.join(QStringLiteral(" "));
}

void recordFileStats(FileStats& stats, const QString& relativePath) {
    ++stats.totalFiles;

    const QString suffix = lowerSuffix(relativePath);
    const QString fileName = lowerFileName(relativePath);
    if (isQmlLikeFile(suffix)) {
        ++stats.qmlFiles;
    }
    if (suffix == QStringLiteral("html") || suffix == QStringLiteral("htm")) {
        ++stats.htmlFiles;
    }
    if (suffix == QStringLiteral("css") || suffix == QStringLiteral("scss")) {
        ++stats.cssFiles;
    }
    if (suffix == QStringLiteral("js") || suffix == QStringLiteral("mjs") ||
        suffix == QStringLiteral("cjs") || suffix == QStringLiteral("ts") ||
        suffix == QStringLiteral("tsx") || suffix == QStringLiteral("mts") ||
        suffix == QStringLiteral("cts")) {
        ++stats.webScriptFiles;
    }
    if (isCppLikeFile(suffix) || isManifestFileName(fileName)) {
        ++stats.cppFiles;
    }
    if (suffix == QStringLiteral("json")) {
        ++stats.jsonFiles;
    }
}

void recordScopeStats(QHash<QString, FileStats>& statsByScope, const QString& scope, const QString& relativePath) {
    const QString cleanedScope = normalizePath(scope);
    if (cleanedScope.isEmpty()) {
        return;
    }
    recordFileStats(statsByScope[cleanedScope], relativePath);
}

QString detectProjectKind(const QString& projectRootPath) {
    const QDir rootDir(projectRootPath);
    const QFileInfoList fileInfos =
        rootDir.entryInfoList(QDir::Files | QDir::NoDotAndDotDot);
    bool hasCMake = false;
    bool hasQmlProject = false;
    bool hasPackageJson = false;
    bool hasPom = false;
    bool hasGradle = false;

    for (const QFileInfo& fileInfo : fileInfos) {
        const QString nameLower = fileInfo.fileName().trimmed().toLower();
        if (nameLower == QStringLiteral("cmakelists.txt")) {
            hasCMake = true;
        } else if (fileInfo.suffix().trimmed().toLower() == QStringLiteral("qmlproject")) {
            hasQmlProject = true;
        } else if (nameLower == QStringLiteral("package.json")) {
            hasPackageJson = true;
        } else if (nameLower == QStringLiteral("pom.xml")) {
            hasPom = true;
        } else if (nameLower == QStringLiteral("build.gradle") ||
                   nameLower == QStringLiteral("build.gradle.kts")) {
            hasGradle = true;
        }
    }

    if (hasCMake && hasQmlProject) {
        return QStringLiteral("CMake + QML");
    }
    if (hasQmlProject) {
        return QStringLiteral("QML Project");
    }
    if (hasCMake) {
        return QStringLiteral("CMake / C++");
    }
    if (hasPackageJson) {
        return QStringLiteral("Node / Web");
    }
    if (hasPom || hasGradle) {
        return QStringLiteral("JVM");
    }
    return QStringLiteral("通用工程");
}

void scanRootDirectories(const QString& projectRootPath, ScanResult& result) {
    const QDir rootDir(projectRootPath);
    const QFileInfoList directoryInfos =
        rootDir.entryInfoList(QDir::Dirs | QDir::NoDotAndDotDot | QDir::Hidden | QDir::System);

    for (const QFileInfo& directoryInfo : directoryInfos) {
        const QString relativePath = directoryInfo.fileName().trimmed();
        const QString nameLower = relativePath.toLower();
        appendUniqueString(result.rootDirectories, relativePath);

        if (isHighConfidenceIgnoreDirectoryName(nameLower)) {
            appendUniqueString(result.highConfidenceIgnoreDirectories, relativePath);
            continue;
        }
        if (isAmbiguousGeneratedDirectoryName(nameLower)) {
            appendUniqueString(result.ambiguousGeneratedDirectories, relativePath);
            continue;
        }
        if (isOptionalNoiseDirectoryName(nameLower)) {
            appendUniqueString(result.optionalIgnoreDirectories, relativePath);
            continue;
        }
        if (isDependencyDirectoryName(nameLower)) {
            appendUniqueString(result.dependencyDirectories, relativePath);
        }
    }
}

void parseQmlProjectHints(const QString& filePath, ScanResult& result) {
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return;
    }

    const QString text = QString::fromUtf8(file.readAll());
    static const QRegularExpression mainFilePattern(
        QStringLiteral(R"regex(\bmainFile\s*:\s*"([^"]+)")regex"));
    static const QRegularExpression mainUiFilePattern(
        QStringLiteral(R"regex(\bmainUiFile\s*:\s*"([^"]+)")regex"));

    for (const auto& pattern : {mainFilePattern, mainUiFilePattern}) {
        auto iterator = pattern.globalMatch(text);
        while (iterator.hasNext()) {
            const auto match = iterator.next();
            const QString prefix = entryPrefixForFilePath(match.captured(1));
            if (prefix.isEmpty()) {
                continue;
            }
            appendUniqueReason(
                result.entryReasons,
                prefix,
                QStringLiteral("检测到 QML 工程入口文件落在这里。"));
            appendUniqueReason(
                result.presentationReasons,
                prefix,
                QStringLiteral("这里承接了 QML 主界面文件。"));
        }
    }
}

void detectModuleMergePairs(const QString& projectRootPath, ScanResult& result) {
    const QDir rootDir(projectRootPath);
    QSet<QString> seenKeys;

    const auto addMergeRule = [&](const QString& scope) {
        const QString cleanedScope = normalizePath(scope);
        if (cleanedScope.isEmpty()) {
            return;
        }

        const QDir scopeDir(rootDir.filePath(cleanedScope));
        const QFileInfo includeInfo(scopeDir.filePath(QStringLiteral("include")));
        const QFileInfo srcInfo(scopeDir.filePath(QStringLiteral("src")));
        if (!includeInfo.exists() || !includeInfo.isDir() ||
            !srcInfo.exists() || !srcInfo.isDir()) {
            return;
        }

        const auto appendRule = [&](const QString& suffix) {
            QVariantMap rule;
            rule.insert(QStringLiteral("match"), normalizePath(cleanedScope + QLatin1Char('/') + suffix));
            rule.insert(QStringLiteral("target"), cleanedScope);
            const QString key =
                rule.value(QStringLiteral("match")).toString() +
                QStringLiteral("->") +
                rule.value(QStringLiteral("target")).toString();
            if (!seenKeys.contains(key)) {
                seenKeys.insert(key);
                result.moduleMerges.push_back(rule);
            }
        };

        appendRule(QStringLiteral("include"));
        appendRule(QStringLiteral("src"));
    };

    const QFileInfoList topLevelDirectories =
        rootDir.entryInfoList(QDir::Dirs | QDir::NoDotAndDotDot | QDir::Hidden | QDir::System);
    for (const QFileInfo& topLevel : topLevelDirectories) {
        const QString topLevelPath = topLevel.fileName().trimmed();
        const QString nameLower = topLevelPath.toLower();
        if (isHighConfidenceIgnoreDirectoryName(nameLower) ||
            isAmbiguousGeneratedDirectoryName(nameLower) ||
            isDependencyDirectoryName(nameLower)) {
            continue;
        }

        addMergeRule(topLevelPath);
        const QDir childRoot(topLevel.absoluteFilePath());
        const QFileInfoList childDirectories =
            childRoot.entryInfoList(QDir::Dirs | QDir::NoDotAndDotDot);
        for (const QFileInfo& child : childDirectories) {
            addMergeRule(normalizePath(topLevelPath + QLatin1Char('/') + child.fileName()));
        }
    }
}

void scanReportBackedHints(
    const savt::core::AnalysisReport& report,
    const savt::core::CapabilityGraph& capabilityGraph,
    ScanResult& result) {
    for (const savt::core::SymbolNode& node : report.nodes) {
        if (node.kind != savt::core::SymbolKind::File) {
            continue;
        }

        const QString relativePath = normalizePath(QString::fromStdString(node.filePath));
        if (relativePath.isEmpty()) {
            continue;
        }

        const QStringList segments = splitSegments(relativePath);
        if (segments.isEmpty()) {
            continue;
        }

        recordScopeStats(result.scopeStats, segments.constFirst(), relativePath);
        if (segments.size() >= 2 && isWebHintName(segments[1].trimmed().toLower())) {
            recordScopeStats(
                result.scopeStats,
                joinSegments({segments[0], segments[1]}),
                relativePath);
        }

        const QString fileNameLower = lowerFileName(relativePath);
        if (isMainLikeFileName(fileNameLower)) {
            const QString prefix = entryPrefixForFilePath(relativePath);
            if (!prefix.isEmpty()) {
                appendUniqueReason(
                    result.entryReasons,
                    prefix,
                    QStringLiteral("检测到典型入口文件 %1。")
                        .arg(QFileInfo(relativePath).fileName()));
            }
        }

        if (fileNameLower == QStringLiteral("main.qml") ||
            fileNameLower == QStringLiteral("app.qml")) {
            const QString prefix = entryPrefixForFilePath(relativePath);
            if (!prefix.isEmpty()) {
                appendUniqueReason(
                    result.presentationReasons,
                    prefix,
                    QStringLiteral("检测到主界面 QML 文件 %1。")
                        .arg(QFileInfo(relativePath).fileName()));
            }
        }
    }

    for (const savt::core::CapabilityNode& node : capabilityGraph.nodes) {
        if (node.kind != savt::core::CapabilityNodeKind::Entry) {
            continue;
        }

        for (const std::string& moduleName : node.moduleNames) {
            const QString candidate = normalizePath(QString::fromStdString(moduleName));
            if (!candidate.isEmpty()) {
                appendUniqueReason(
                    result.entryReasons,
                    candidate,
                    QStringLiteral("当前能力图已经把它识别成入口模块。"));
            }
        }
    }
}

void synthesizeRoleHints(ScanResult& result) {
    QStringList scopes = result.scopeStats.keys();
    std::sort(scopes.begin(), scopes.end(), [](const QString& left, const QString& right) {
        const int depthCompare = splitSegments(left).size() - splitSegments(right).size();
        if (depthCompare != 0) {
            return depthCompare < 0;
        }
        return left < right;
    });

    for (const QString& scope : scopes) {
        const FileStats stats = result.scopeStats.value(scope);
        const QString nameLower = QFileInfo(scope).fileName().trimmed().toLower();
        if (isHighConfidenceIgnoreDirectoryName(nameLower) ||
            isAmbiguousGeneratedDirectoryName(nameLower) ||
            isDependencyDirectoryName(nameLower)) {
            continue;
        }

        const int webWeight = stats.htmlFiles + stats.cssFiles + stats.webScriptFiles;
        if (stats.qmlFiles >= 2 &&
            stats.qmlFiles >= webWeight &&
            (isPresentationHintName(nameLower) ||
             result.presentationReasons.contains(scope))) {
            appendUniqueReason(
                result.presentationReasons,
                scope,
                QStringLiteral("这里以 QML 界面文件为主（%1 个）。")
                    .arg(stats.qmlFiles));
        }

        if ((isWebHintName(nameLower) || scope.toLower().contains(QStringLiteral("/web"))) &&
            (stats.htmlFiles > 0 || stats.cssFiles > 0)) {
            appendUniqueReason(
                result.webReasons,
                scope,
                QStringLiteral("这里包含 HTML/CSS 页面资源。"));
        }
    }
}

QVariantList toVariantStringList(const QStringList& values) {
    QVariantList items;
    for (const QString& value : values) {
        const QString cleaned = normalizePath(value);
        if (!cleaned.isEmpty()) {
            items.push_back(cleaned);
        }
    }
    return items;
}

QVariantMap makeOption(
    const QString& id,
    const QString& label,
    const QString& description,
    const QVariantMap& effects) {
    QVariantMap option;
    option.insert(QStringLiteral("id"), id);
    option.insert(QStringLiteral("label"), label);
    option.insert(QStringLiteral("description"), description);
    option.insert(QStringLiteral("effects"), effects);
    return option;
}

QVariantMap ignoreEffects(const QStringList& directories) {
    QVariantMap effects;
    effects.insert(QStringLiteral("ignoreDirectories"), toVariantStringList(directories));
    return effects;
}

QVariantMap roleEffects(const QString& match, const QString& role) {
    QVariantMap effects;
    QVariantMap rule;
    rule.insert(QStringLiteral("match"), normalizePath(match));
    rule.insert(QStringLiteral("role"), role.trimmed().toLower());
    effects.insert(QStringLiteral("roleOverrides"), QVariantList{rule});
    return effects;
}

QVariantMap entryEffects(const QString& match, const bool entry) {
    QVariantMap effects;
    QVariantMap rule;
    rule.insert(QStringLiteral("match"), normalizePath(match));
    rule.insert(QStringLiteral("entry"), entry);
    effects.insert(QStringLiteral("entryOverrides"), QVariantList{rule});
    return effects;
}

QVariantMap buildChoice(
    const QString& id,
    const QString& title,
    const QString& summary,
    const QString& selectedOptionId,
    const QVariantList& options) {
    QVariantMap choice;
    choice.insert(QStringLiteral("id"), id);
    choice.insert(QStringLiteral("title"), title);
    choice.insert(QStringLiteral("summary"), summary);
    choice.insert(QStringLiteral("selectedOptionId"), selectedOptionId);
    choice.insert(QStringLiteral("options"), options);
    return choice;
}

QVariantList buildChoiceItems(const ScanResult& scan) {
    QVariantList choices;

    for (const QString& path : scan.ambiguousGeneratedDirectories) {
        choices.push_back(buildChoice(
            QStringLiteral("generated:") + path,
            QStringLiteral("%1 目录怎么处理").arg(path),
            QStringLiteral("这个目录名字很像生成产物，继续纳入分析容易把主图面拖脏。"),
            QStringLiteral("ignore"),
            QVariantList{
                makeOption(
                    QStringLiteral("ignore"),
                    QStringLiteral("忽略"),
                    QStringLiteral("把它排除在分析之外。"),
                    ignoreEffects({path})),
                makeOption(
                    QStringLiteral("keep"),
                    QStringLiteral("保留"),
                    QStringLiteral("继续让它参与分析。"),
                    {})
            }));
    }

    if (!scan.optionalIgnoreDirectories.isEmpty()) {
        choices.push_back(buildChoice(
            QStringLiteral("optional-ignore"),
            QStringLiteral("测试与示例目录"),
            QStringLiteral("检测到 %1。它们会增加阅读噪音，但有些项目又希望把它们保留下来。")
                .arg(scan.optionalIgnoreDirectories.join(QStringLiteral("、"))),
            QStringLiteral("ignore"),
            QVariantList{
                makeOption(
                    QStringLiteral("ignore"),
                    QStringLiteral("先忽略"),
                    QStringLiteral("把这些目录先从主分析里拿掉。"),
                    ignoreEffects(scan.optionalIgnoreDirectories)),
                makeOption(
                    QStringLiteral("keep"),
                    QStringLiteral("全部保留"),
                    QStringLiteral("继续把它们算进项目结构。"),
                    {})
            }));
    }

    QStringList presentationScopes = scan.presentationReasons.keys();
    std::sort(presentationScopes.begin(), presentationScopes.end());
    if (presentationScopes.size() > 3) {
        presentationScopes = presentationScopes.mid(0, 3);
    }
    for (const QString& path : presentationScopes) {
        choices.push_back(buildChoice(
            QStringLiteral("presentation:") + path,
            QStringLiteral("%1 的角色").arg(path),
            summarizeReasons(
                scan.presentationReasons.value(path),
                QStringLiteral("这里看起来更像界面承载层。")),
            QStringLiteral("presentation"),
            QVariantList{
                makeOption(
                    QStringLiteral("presentation"),
                    QStringLiteral("界面层"),
                    QStringLiteral("按展示层来解释它。"),
                    roleEffects(path, QStringLiteral("presentation"))),
                makeOption(
                    QStringLiteral("default"),
                    QStringLiteral("保持默认"),
                    QStringLiteral("先不强行覆盖角色。"),
                    {})
            }));
    }

    QStringList webScopes = scan.webReasons.keys();
    std::sort(webScopes.begin(), webScopes.end());
    if (webScopes.size() > 2) {
        webScopes = webScopes.mid(0, 2);
    }
    for (const QString& path : webScopes) {
        choices.push_back(buildChoice(
            QStringLiteral("web:") + path,
            QStringLiteral("%1 的角色").arg(path),
            summarizeReasons(
                scan.webReasons.value(path),
                QStringLiteral("这里更像 Web 页面与资源承载层。")),
            QStringLiteral("web"),
            QVariantList{
                makeOption(
                    QStringLiteral("web"),
                    QStringLiteral("Web 承载"),
                    QStringLiteral("把它标成 Web 资源区域。"),
                    roleEffects(path, QStringLiteral("web"))),
                makeOption(
                    QStringLiteral("default"),
                    QStringLiteral("保持默认"),
                    QStringLiteral("先不强行覆盖角色。"),
                    {})
            }));
    }

    QStringList entryScopes = scan.entryReasons.keys();
    std::sort(entryScopes.begin(), entryScopes.end());
    if (entryScopes.size() > 4) {
        entryScopes = entryScopes.mid(0, 4);
    }
    for (const QString& path : entryScopes) {
        choices.push_back(buildChoice(
            QStringLiteral("entry:") + path,
            QStringLiteral("%1 是否标成入口").arg(path),
            summarizeReasons(
                scan.entryReasons.value(path),
                QStringLiteral("这里可能是项目的启动或主界面入口。")),
            QStringLiteral("entry"),
            QVariantList{
                makeOption(
                    QStringLiteral("entry"),
                    QStringLiteral("标记入口"),
                    QStringLiteral("让 SAVT 把它当成主入口之一。"),
                    entryEffects(path, true)),
                makeOption(
                    QStringLiteral("default"),
                    QStringLiteral("保持默认"),
                    QStringLiteral("继续沿用自动推断。"),
                    {})
            }));
    }

    return choices;
}

QString moduleMergeKey(const QVariantMap& item) {
    return normalizePath(item.value(QStringLiteral("match")).toString()) +
           QStringLiteral("->") +
           normalizePath(item.value(QStringLiteral("target")).toString());
}

QString roleOverrideKey(const QVariantMap& item) {
    return normalizePath(item.value(QStringLiteral("match")).toString()) +
           QStringLiteral("->") +
           item.value(QStringLiteral("role")).toString().trimmed().toLower();
}

QString entryOverrideKey(const QVariantMap& item) {
    return normalizePath(item.value(QStringLiteral("match")).toString()) +
           QStringLiteral("->") +
           QString::number(item.value(QStringLiteral("entry")).toBool() ? 1 : 0);
}

QString dependencyFoldKey(const QVariantMap& item) {
    return normalizePath(item.value(QStringLiteral("match")).toString()) +
           QStringLiteral("->") +
           QString::number(item.value(QStringLiteral("collapse")).toBool() ? 1 : 0) +
           QStringLiteral("/") +
           QString::number(item.value(QStringLiteral("hideByDefault")).toBool() ? 1 : 0);
}

RuleSet ruleSetFromVariantMap(const QVariantMap& data) {
    RuleSet ruleSet;
    for (const QVariant& item : data.value(QStringLiteral("ignoreDirectories")).toList()) {
        appendUniqueString(ruleSet.ignoreDirectories, item.toString());
    }
    for (const QVariant& item : data.value(QStringLiteral("moduleMerges")).toList()) {
        const QVariantMap map = item.toMap();
        if (!map.isEmpty()) {
            ruleSet.moduleMerges.push_back(map);
        }
    }
    for (const QVariant& item : data.value(QStringLiteral("roleOverrides")).toList()) {
        const QVariantMap map = item.toMap();
        if (!map.isEmpty()) {
            ruleSet.roleOverrides.push_back(map);
        }
    }
    for (const QVariant& item : data.value(QStringLiteral("entryOverrides")).toList()) {
        const QVariantMap map = item.toMap();
        if (!map.isEmpty()) {
            ruleSet.entryOverrides.push_back(map);
        }
    }
    for (const QVariant& item : data.value(QStringLiteral("dependencyFoldRules")).toList()) {
        const QVariantMap map = item.toMap();
        if (!map.isEmpty()) {
            ruleSet.dependencyFoldRules.push_back(map);
        }
    }
    return ruleSet;
}

void appendRuleSet(RuleSet& destination, const RuleSet& additions) {
    for (const QString& value : additions.ignoreDirectories) {
        appendUniqueString(destination.ignoreDirectories, value);
    }

    const auto appendUniqueRule = [](QList<QVariantMap>& destinationList,
                                     const QList<QVariantMap>& additionsList,
                                     const auto& keyBuilder) {
        QSet<QString> seenKeys;
        for (const QVariantMap& item : destinationList) {
            seenKeys.insert(keyBuilder(item));
        }
        for (const QVariantMap& item : additionsList) {
            const QString key = keyBuilder(item);
            if (!key.isEmpty() && !seenKeys.contains(key)) {
                seenKeys.insert(key);
                destinationList.push_back(item);
            }
        }
    };

    appendUniqueRule(destination.moduleMerges, additions.moduleMerges, moduleMergeKey);
    appendUniqueRule(destination.roleOverrides, additions.roleOverrides, roleOverrideKey);
    appendUniqueRule(destination.entryOverrides, additions.entryOverrides, entryOverrideKey);
    appendUniqueRule(destination.dependencyFoldRules, additions.dependencyFoldRules, dependencyFoldKey);
}

QVariantMap ruleSetToVariantMap(RuleSet ruleSet) {
    std::sort(ruleSet.ignoreDirectories.begin(), ruleSet.ignoreDirectories.end());
    const auto sortRules = [](QList<QVariantMap>& values, const auto& keyBuilder) {
        std::sort(values.begin(), values.end(), [&](const QVariantMap& left, const QVariantMap& right) {
            return keyBuilder(left) < keyBuilder(right);
        });
    };
    sortRules(ruleSet.moduleMerges, moduleMergeKey);
    sortRules(ruleSet.roleOverrides, roleOverrideKey);
    sortRules(ruleSet.entryOverrides, entryOverrideKey);
    sortRules(ruleSet.dependencyFoldRules, dependencyFoldKey);

    QVariantMap map;
    map.insert(QStringLiteral("ignoreDirectories"), toVariantStringList(ruleSet.ignoreDirectories));

    QVariantList moduleMerges;
    for (const QVariantMap& item : ruleSet.moduleMerges) {
        moduleMerges.push_back(item);
    }
    map.insert(QStringLiteral("moduleMerges"), moduleMerges);

    QVariantList roleOverrides;
    for (const QVariantMap& item : ruleSet.roleOverrides) {
        roleOverrides.push_back(item);
    }
    map.insert(QStringLiteral("roleOverrides"), roleOverrides);

    QVariantList entryOverrides;
    for (const QVariantMap& item : ruleSet.entryOverrides) {
        entryOverrides.push_back(item);
    }
    map.insert(QStringLiteral("entryOverrides"), entryOverrides);

    QVariantList dependencyFoldRules;
    for (const QVariantMap& item : ruleSet.dependencyFoldRules) {
        dependencyFoldRules.push_back(item);
    }
    map.insert(QStringLiteral("dependencyFoldRules"), dependencyFoldRules);
    return map;
}

QJsonArray stringArray(const QVariantList& values) {
    QJsonArray array;
    for (const QVariant& value : values) {
        const QString cleaned = normalizePath(value.toString());
        if (!cleaned.isEmpty()) {
            array.push_back(cleaned);
        }
    }
    return array;
}

QJsonArray moduleMergeArray(const QVariantList& values) {
    QJsonArray array;
    for (const QVariant& value : values) {
        const QVariantMap map = value.toMap();
        const QString match = normalizePath(map.value(QStringLiteral("match")).toString());
        const QString target = normalizePath(map.value(QStringLiteral("target")).toString());
        if (match.isEmpty() || target.isEmpty()) {
            continue;
        }
        QJsonObject item;
        item.insert(QStringLiteral("match"), match);
        item.insert(QStringLiteral("module"), target);
        array.push_back(item);
    }
    return array;
}

QJsonArray roleOverrideArray(const QVariantList& values) {
    QJsonArray array;
    for (const QVariant& value : values) {
        const QVariantMap map = value.toMap();
        const QString match = normalizePath(map.value(QStringLiteral("match")).toString());
        const QString role = map.value(QStringLiteral("role")).toString().trimmed().toLower();
        if (match.isEmpty() || role.isEmpty()) {
            continue;
        }
        QJsonObject item;
        item.insert(QStringLiteral("match"), match);
        item.insert(QStringLiteral("role"), role);
        array.push_back(item);
    }
    return array;
}

QJsonArray entryOverrideArray(const QVariantList& values) {
    QJsonArray array;
    for (const QVariant& value : values) {
        const QVariantMap map = value.toMap();
        const QString match = normalizePath(map.value(QStringLiteral("match")).toString());
        if (match.isEmpty()) {
            continue;
        }
        QJsonObject item;
        item.insert(QStringLiteral("match"), match);
        item.insert(QStringLiteral("entry"), map.value(QStringLiteral("entry")).toBool());
        array.push_back(item);
    }
    return array;
}

QJsonArray dependencyFoldArray(const QVariantList& values) {
    QJsonArray array;
    for (const QVariant& value : values) {
        const QVariantMap map = value.toMap();
        const QString match = normalizePath(map.value(QStringLiteral("match")).toString());
        if (match.isEmpty()) {
            continue;
        }
        QJsonObject item;
        item.insert(QStringLiteral("match"), match);
        item.insert(QStringLiteral("collapse"), map.value(QStringLiteral("collapse")).toBool());
        item.insert(QStringLiteral("hideByDefault"), map.value(QStringLiteral("hideByDefault")).toBool());
        array.push_back(item);
    }
    return array;
}

QVariantMap countsForDraft(const QVariantMap& draftConfig) {
    QVariantMap counts;
    counts.insert(
        QStringLiteral("ignore"),
        static_cast<qulonglong>(draftConfig.value(QStringLiteral("ignoreDirectories")).toList().size()));
    counts.insert(
        QStringLiteral("merge"),
        static_cast<qulonglong>(draftConfig.value(QStringLiteral("moduleMerges")).toList().size()));
    counts.insert(
        QStringLiteral("role"),
        static_cast<qulonglong>(draftConfig.value(QStringLiteral("roleOverrides")).toList().size()));
    counts.insert(
        QStringLiteral("entry"),
        static_cast<qulonglong>(draftConfig.value(QStringLiteral("entryOverrides")).toList().size()));
    counts.insert(
        QStringLiteral("fold"),
        static_cast<qulonglong>(draftConfig.value(QStringLiteral("dependencyFoldRules")).toList().size()));
    return counts;
}

QString renderDraftJson(const QVariantMap& draftConfig) {
    QJsonObject analysis;

    const QJsonArray ignoreDirectories =
        stringArray(draftConfig.value(QStringLiteral("ignoreDirectories")).toList());
    if (!ignoreDirectories.isEmpty()) {
        analysis.insert(QStringLiteral("ignoreDirectories"), ignoreDirectories);
    }

    const QJsonArray moduleMerges =
        moduleMergeArray(draftConfig.value(QStringLiteral("moduleMerges")).toList());
    if (!moduleMerges.isEmpty()) {
        analysis.insert(QStringLiteral("moduleMerges"), moduleMerges);
    }

    const QJsonArray roleOverrides =
        roleOverrideArray(draftConfig.value(QStringLiteral("roleOverrides")).toList());
    if (!roleOverrides.isEmpty()) {
        analysis.insert(QStringLiteral("roleOverrides"), roleOverrides);
    }

    const QJsonArray entryOverrides =
        entryOverrideArray(draftConfig.value(QStringLiteral("entryOverrides")).toList());
    if (!entryOverrides.isEmpty()) {
        analysis.insert(QStringLiteral("entryOverrides"), entryOverrides);
    }

    const QJsonArray dependencyFoldRules =
        dependencyFoldArray(draftConfig.value(QStringLiteral("dependencyFoldRules")).toList());
    if (!dependencyFoldRules.isEmpty()) {
        analysis.insert(QStringLiteral("dependencyFoldRules"), dependencyFoldRules);
    }

    QJsonObject root;
    root.insert(QStringLiteral("version"), 1);
    root.insert(QStringLiteral("analysis"), analysis);
    return QString::fromUtf8(QJsonDocument(root).toJson(QJsonDocument::Indented)).trimmed() +
           QLatin1Char('\n');
}

QVariantMap recomputeRecommendation(QVariantMap recommendation) {
    RuleSet resolved = ruleSetFromVariantMap(recommendation.value(QStringLiteral("baseConfig")).toMap());
    const QVariantList choices = recommendation.value(QStringLiteral("choiceItems")).toList();
    for (const QVariant& choiceValue : choices) {
        const QVariantMap choice = choiceValue.toMap();
        const QString selectedOptionId =
            choice.value(QStringLiteral("selectedOptionId")).toString().trimmed();
        for (const QVariant& optionValue : choice.value(QStringLiteral("options")).toList()) {
            const QVariantMap option = optionValue.toMap();
            if (option.value(QStringLiteral("id")).toString().trimmed() != selectedOptionId) {
                continue;
            }
            appendRuleSet(
                resolved,
                ruleSetFromVariantMap(option.value(QStringLiteral("effects")).toMap()));
            break;
        }
    }

    const QVariantMap draftConfig = ruleSetToVariantMap(std::move(resolved));
    recommendation.insert(QStringLiteral("draftConfig"), draftConfig);
    recommendation.insert(QStringLiteral("draftCounts"), countsForDraft(draftConfig));
    recommendation.insert(QStringLiteral("draftJson"), renderDraftJson(draftConfig));
    recommendation.insert(QStringLiteral("uncertainCount"), choices.size());
    recommendation.insert(QStringLiteral("hasUncertainChoices"), !choices.isEmpty());
    recommendation.insert(
        QStringLiteral("decisionHint"),
        choices.isEmpty()
            ? QStringLiteral("这份草案没有额外的手动选择项，可以直接生成。")
            : QStringLiteral("下面这些地方我先按推荐值选好了，你可以改完再生成。"));
    recommendation.insert(
        QStringLiteral("tone"),
        choices.isEmpty() ? QStringLiteral("success") : QStringLiteral("warning"));
    return recommendation;
}

ScanResult buildScanResult(
    const QString& projectRootPath,
    const savt::core::AnalysisReport& report,
    const savt::core::CapabilityGraph& capabilityGraph) {
    ScanResult result;
    result.projectKindLabel = detectProjectKind(projectRootPath);
    scanRootDirectories(projectRootPath, result);
    detectModuleMergePairs(projectRootPath, result);

    const QDir rootDir(projectRootPath);
    const QFileInfoList rootFiles =
        rootDir.entryInfoList(QDir::Files | QDir::NoDotAndDotDot);
    for (const QFileInfo& rootFile : rootFiles) {
        if (rootFile.suffix().trimmed().toLower() == QStringLiteral("qmlproject")) {
            parseQmlProjectHints(rootFile.absoluteFilePath(), result);
        }
    }

    scanReportBackedHints(report, capabilityGraph, result);
    synthesizeRoleHints(result);
    return result;
}

}  // namespace

QVariantMap ProjectConfigRecommendationService::buildRecommendation(
    const QString& projectRootPath,
    const savt::core::AnalysisReport& report,
    const savt::core::ArchitectureOverview&,
    const savt::core::CapabilityGraph& capabilityGraph) {
    QVariantMap recommendation;

    const QString cleanedRoot = QDir::cleanPath(projectRootPath.trimmed());
    const QFileInfo rootInfo(cleanedRoot);
    if (cleanedRoot.isEmpty() || !rootInfo.exists() || !rootInfo.isDir()) {
        recommendation.insert(QStringLiteral("available"), false);
        recommendation.insert(QStringLiteral("canGenerate"), false);
        recommendation.insert(QStringLiteral("summary"), QStringLiteral("先选择一个可访问的项目目录。"));
        recommendation.insert(QStringLiteral("targetPath"), QString());
        recommendation.insert(QStringLiteral("choiceItems"), QVariantList{});
        recommendation.insert(QStringLiteral("baseConfig"), QVariantMap{});
        recommendation.insert(QStringLiteral("draftConfig"), QVariantMap{});
        recommendation.insert(QStringLiteral("draftCounts"), QVariantMap{});
        recommendation.insert(QStringLiteral("draftJson"), QString());
        recommendation.insert(QStringLiteral("writeActionLabel"), QStringLiteral("生成配置"));
        recommendation.insert(QStringLiteral("tone"), QStringLiteral("info"));
        recommendation.insert(QStringLiteral("uncertainCount"), 0);
        return recommendation;
    }

    const auto existingConfig = savt::core::loadProjectAnalysisConfig(
        std::filesystem::path(QDir::fromNativeSeparators(cleanedRoot).toStdString()));
    const QString normalizedTargetPath =
        !existingConfig.configPath.empty()
            ? normalizePath(QString::fromStdString(existingConfig.configPath))
            : normalizePath(QDir(cleanedRoot).filePath(QStringLiteral(".savt/project.json")));

    const ScanResult scan = buildScanResult(cleanedRoot, report, capabilityGraph);

    RuleSet baseRules;
    for (const QString& directory : scan.highConfidenceIgnoreDirectories) {
        appendUniqueString(baseRules.ignoreDirectories, directory);
    }
    for (const QVariantMap& rule : scan.moduleMerges) {
        baseRules.moduleMerges.push_back(rule);
    }
    for (const QString& directory : scan.dependencyDirectories) {
        QVariantMap rule;
        rule.insert(QStringLiteral("match"), normalizePath(directory));
        rule.insert(QStringLiteral("collapse"), true);
        rule.insert(QStringLiteral("hideByDefault"), true);
        baseRules.dependencyFoldRules.push_back(rule);
    }

    const QVariantList choiceItems = buildChoiceItems(scan);
    recommendation.insert(QStringLiteral("available"), true);
    recommendation.insert(QStringLiteral("canGenerate"), true);
    recommendation.insert(QStringLiteral("projectKindLabel"), scan.projectKindLabel);
    recommendation.insert(QStringLiteral("targetPath"), nativePath(normalizedTargetPath));
    recommendation.insert(QStringLiteral("targetPathNormalized"), normalizedTargetPath);
    recommendation.insert(QStringLiteral("baseConfig"), ruleSetToVariantMap(baseRules));
    recommendation.insert(QStringLiteral("choiceItems"), choiceItems);
    recommendation.insert(
        QStringLiteral("writeActionLabel"),
        existingConfig.configPath.empty()
            ? QStringLiteral("生成配置")
            : QStringLiteral("重写配置"));
    recommendation.insert(QStringLiteral("hasExistingConfig"), !existingConfig.configPath.empty());
    recommendation.insert(QStringLiteral("existingConfigLoaded"), existingConfig.loaded);
    recommendation.insert(
        QStringLiteral("summary"),
        choiceItems.isEmpty()
            ? QStringLiteral("检测到 %1 工程。我已经整理出一份可以直接落盘的 SAVT 配置草案。")
                  .arg(scan.projectKindLabel)
            : QStringLiteral("检测到 %1 工程。我先补好了高置信规则，并把 %2 处拿不准的地方留成可切换选项。")
                  .arg(scan.projectKindLabel)
                  .arg(choiceItems.size()));
    return recomputeRecommendation(std::move(recommendation));
}

QVariantMap ProjectConfigRecommendationService::selectChoice(
    const QVariantMap& recommendation,
    const QString& choiceId,
    const QString& optionId) {
    QVariantMap updated = recommendation;
    QVariantList choices = updated.value(QStringLiteral("choiceItems")).toList();
    for (QVariant& choiceValue : choices) {
        QVariantMap choice = choiceValue.toMap();
        if (choice.value(QStringLiteral("id")).toString().trimmed() != choiceId.trimmed()) {
            continue;
        }

        bool optionFound = false;
        for (const QVariant& optionValue : choice.value(QStringLiteral("options")).toList()) {
            if (optionValue.toMap().value(QStringLiteral("id")).toString().trimmed() == optionId.trimmed()) {
                optionFound = true;
                break;
            }
        }
        if (!optionFound) {
            return recommendation;
        }

        choice.insert(QStringLiteral("selectedOptionId"), optionId.trimmed());
        choiceValue = choice;
        updated.insert(QStringLiteral("choiceItems"), choices);
        return recomputeRecommendation(std::move(updated));
    }

    return recommendation;
}

bool ProjectConfigRecommendationService::writeRecommendation(
    const QString& projectRootPath,
    const QVariantMap& recommendation,
    QString* writtenPath,
    QString* errorMessage) {
    if (writtenPath != nullptr) {
        writtenPath->clear();
    }
    if (errorMessage != nullptr) {
        errorMessage->clear();
    }

    const QString cleanedRoot = QDir::cleanPath(projectRootPath.trimmed());
    const QFileInfo rootInfo(cleanedRoot);
    if (cleanedRoot.isEmpty() || !rootInfo.exists() || !rootInfo.isDir()) {
        if (errorMessage != nullptr) {
            *errorMessage = QStringLiteral("当前项目目录不可访问，暂时没法写入配置文件。");
        }
        return false;
    }

    const QString draftJson = recommendation.value(QStringLiteral("draftJson")).toString();
    if (draftJson.trimmed().isEmpty()) {
        if (errorMessage != nullptr) {
            *errorMessage = QStringLiteral("当前草案为空，暂时没有可写入的配置内容。");
        }
        return false;
    }

    QString targetPath =
        normalizePath(recommendation.value(QStringLiteral("targetPathNormalized")).toString());
    if (targetPath.isEmpty()) {
        targetPath = normalizePath(QDir(cleanedRoot).filePath(QStringLiteral(".savt/project.json")));
    }

    const QFileInfo targetInfo(targetPath);
    QDir parentDir = targetInfo.dir();
    if (!parentDir.exists() && !QDir().mkpath(parentDir.absolutePath())) {
        if (errorMessage != nullptr) {
            *errorMessage = QStringLiteral("没能创建配置目录：%1")
                                .arg(QDir::toNativeSeparators(parentDir.absolutePath()));
        }
        return false;
    }

    QFile output(targetPath);
    if (!output.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        if (errorMessage != nullptr) {
            *errorMessage = QStringLiteral("没能写入配置文件：%1")
                                .arg(QDir::toNativeSeparators(targetPath));
        }
        return false;
    }

    if (output.write(draftJson.toUtf8()) < 0) {
        if (errorMessage != nullptr) {
            *errorMessage = QStringLiteral("写入配置文件时失败了：%1")
                                .arg(QDir::toNativeSeparators(targetPath));
        }
        return false;
    }

    output.close();
    if (writtenPath != nullptr) {
        *writtenPath = QDir::toNativeSeparators(targetPath);
    }
    return true;
}

}  // namespace savt::ui
